# Generated by Django 5.0.2 on 2024-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_id'),
        ('products', '0003_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
