# Generated by Django 5.0.2 on 2024-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_id'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(null=True, to='orders.order'),
        ),
    ]
