# Generated by Django 5.0.2 on 2024-02-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(default=False, max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('orders', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(default=False, max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('farm_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
