# Generated by Django 5.0.2 on 2024-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
